### PR TITLE
Help us Review our first OOP milestone. 

### PR DESCRIPTION
**Pull request by rootDEV2990**
Added basic files for project. Thanks for your input.

### CODE REVIEW

**Comment by rootDEV2990** [comment]
Last changes made. Fingers crossed. 🤞

**Review by serdg0 — CHANGES_REQUESTED** [review]
Hello @rootDEV2990 @Joecleverman :v: :peace_symbol:  

Good work, we only need add a minor feature in order to get this milestone approved.

- [ ] Make the main script a bash command. Here is an article to help: https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/



Add the feature and submit for CRR.

**Happy Coding!** :computer: :computer: :nerd_face: 
_**Sergio Diaz**_

**Comment by rootDEV2990** [comment]
Added line for auto ruby env from bash.

**Review by mikenath223 — APPROVED** [review]
### Hi @rootDEV2990  👋

You've done well since the last review.🚀

However, kindly add `.DS_Store` file to `.gitignore` but since it has been committed already consider removing it from the list of git tracked files before adding it to `.gitignore`, use [this link](https://stackoverflow.com/a/1274447/12217655) for a guide on how to do that.

Trusting you will fix this before merging to the default beach, hence this pull request will be approved.

**STATUS: APPROVED ✅**

Don't forget to fill the project completion form👍
**However, kindly make the recommended change before merging to the default branch.👌**

Good luck with the next project.

HAPPY CODING👨‍💻

**Comment by Joecleverman** [comment]
recommended change done!

**Comment by Joecleverman** [comment]
We did the recommended changes and merge as the TS's suggested it but the status did not change

**Pull request merged**
