### PR TITLE
I just completet the test for the Tictactoe, can I have a review please?

### PR DESCRIPTION
**Pull request by Joecleverman**
Create spec folder
- board_spec.rb
-main_spec.rb
-player_spec.rb
 Just run rspec and the output should be : 8 examples, 0 failures
Thanks

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

Hi team :wave: 

You have made good progress so far. However, you need to write more tests...

- [x]  All the public methods of the classes implemented in project OOP are tested ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/all_tic_tac_toe.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

- [x] Also, note; specs for each method should be wrapped in one `describe` block. As in example here https://github.com/rubocop-hq/rspec-style-guide#empty-lines-around-examples . ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/describe.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

That's it; update your test files, then submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 


``` Uchechukwu Henry Inyama```

**Comment by Joecleverman** [comment]
Fixed the required changes

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, great job with this project :+1: You did a great job fixing the comments from the previous TSE :100: Awesome!!! However, let us fix the comments below:

- Let us move the `board test` into the `board_spec.rb` file. And let us remove all the comments
- Let us have a separate file for our `player` test
- Let us move the `game test` into a separate file

Kindly fix these comments and submit another code review :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by Joecleverman** [comment]
All require changes fixed

**Review by lucasmazo32 — APPROVED** [review]
# Project approved :rocket:

#### Great job!

#### Your project looks great!

### You can go ahead and merge this pull request!

### Happy coding! :computer:

## Lucas Mazo

**Pull request merged**
